# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
weight = 1

[he]
languageName = "Hebrew"
languagedirection = "rtl"
title = "הבלוג הרנדומלי של אשלי"
weight = 1
