# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/leeashlee"

[social.params]
icon = "brand-github"

[[social]]
identifier = "matrix"
name = "Matrix"
url = "https://matrix.to/#/@ashleehee:beeper.com"

[social.params]
icon = "brand-matrix"

[[social]]
identifier = "rss"
name = "RSS reader"
url = "https://rss.app/feeds/kLlhruVQVNw3NQg5.xml"

[social.params]
icon = "brand-rss"
